# Generated by Django 2.0.6 on 2018-06-12 07:53

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurableTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_field', models.CharField(max_length=31)),
                ('configurable_setting', jsonfield.fields.JSONField()),
                ('label', models.CharField(max_length=127)),
                ('exceptions', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('required', models.BooleanField()),
                ('active', models.BooleanField()),
                ('disabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=248)),
                ('description', models.CharField(blank=True, max_length=248, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('sheet', jsonfield.fields.JSONField(default=list)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(default='template', max_length=127)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Organisations')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='configurabletemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='firstapp.Template'),
        ),
    ]
