# Generated by Django 2.0.6 on 2018-06-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisations',
            options={'verbose_name_plural': 'Organisations'},
        ),
        migrations.AddField(
            model_name='configurabletemplate',
            name='data_type',
            field=models.CharField(choices=[('int', 'int'), ('str', 'str'), ('singleselect', 'singleselect'), ('multiselect', 'multiselect'), ('table', 'table'), ('date', 'date'), ('float', 'float'), ('bool', 'bool'), ('url', 'url'), ('longstr', 'longstr'), ('file', 'file'), ('image', 'image')], default='int', max_length=31),
        ),
    ]
